---
# Cannot get this to work for some reason
#AWSTemplateFormatVersion: AWSTemplateFormatVersion: '2010-09-09'

Description: This template creates a new VPC and places EC2 Container Service (ECS) into it.

Metadata:
    Foo:
        Description: 'something clever'
    Bar:
        Description: 'something clever'

# These show up in the console and are expected to be provided by the operator
Parameters:
    Project:
        Description: 'Project name this cluster is has been created for'
        Type: 'String'
        Default: 'Weapon X'

    Creator:
        Description: 'Tool or person creating this cluster'
        Type: 'String'
        Default: 'CloudFormation'

    Environment:
        Description: 'Context the cluster will be used in.  Common values are production, testing and development.'
        Type: 'String'
        Default: 'development'

    Notes:
        Description: 'Notes to apply, normally edited in the console.'
        Type: 'String'
        Default: 'No notes'

    SshKeyName:
        Description: 'Name of the key to use when creating the EC2 instances'
        Type: 'String'
        Default: 'asgard-lite-test'

    Network:
        Description: 'The ip range to use when building out the VPC network'
        Type: 'String'
        Default: '10.0.0.0'

    InstanceType:
        Description: 'How large of a box to run your containers on'
        Type: 'String'
        Default: 'm4.large'

    SpotPrice:
        Description: 'Maximum bid price to place on your EC2 instances'
        Type: 'String'
        Default: '0.10'

    VpcURL:
        Description: 'Location of the VPC template file'
        Type: 'String'
        Default: 'https://s3.amazonaws.com/jvmguy-cloudformation-templates/vpc.yml'

    EcsURL:
        Description: 'Location of the ECS template file'
        Type: 'String'
        Default: 'https://s3.amazonaws.com/jvmguy-cloudformation-templates/ecs.yml'

    ElbURL:
        Description: 'Location of the ELB template file'
        Type: 'String'
        Default: 'https://s3.amazonaws.com/jvmguy-cloudformation-templates/elb.yml'

    ServiceURL:
        Description: 'Location of the ECS Service template file'
        Type: 'String'
        Default: 'https://s3.amazonaws.com/jvmguy-cloudformation-templates/service.yml'


Resources:
    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
                Ref: VpcURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes:
                    Ref: Notes
                SshKeyName:
                    Ref: SshKeyName

    ECS:
        Type: AWS::CloudFormation::Stack
        DependsOn: VPC
        Properties:
            TemplateURL:
                Ref: EcsURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes:
                    Ref: Notes
                SshKeyName:
                    Ref: SshKeyName
                InstanceType:
                    Ref: InstanceType
                SpotPrice:
                    Ref: SpotPrice
                Subnets:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.Subnets
                SecurityGroups:
                    Fn::GetAtt:
                        - VPC
                        - Outputs.SecurityGroupWideOpen

    ELB:
        Type: AWS::CloudFormation::Stack
        DependsOn: VPC
        Properties:
            TemplateURL:
                Ref: ElbURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes:
                    Ref: Notes
                Subnets:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.PublicSubnets
                VPC:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.VPC
                SecurityGroups:
                    Fn::GetAtt:
                        - VPC
                        - Outputs.SecurityGroupWideOpen

    Alpha:
        Type: AWS::CloudFormation::Stack
        DependsOn: ELB
        Properties:
            TemplateURL:
                Ref: ServiceURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes:
                    Ref: Notes
                VPC:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.VPC
                Cluster:
                    Fn::GetAtt:
                    - ECS
                    - Outputs.Cluster
                Listener:
                    Fn::GetAtt:
                    - ELB
                    - Outputs.PublicLoadBalancerListener
                Path: '/alpha'
                ContainerName: 'alpha'
