---
# Cannot get this to work for some reason
#AWSTemplateFormatVersion: AWSTemplateFormatVersion: '2010-09-09'

Description: This template creates a new VPC and places EC2 Container Services (ECS) into it.

Metadata:
    Foo:
        Description: 'something clever'
    Bar:
        Description: 'something clever'

# These show up in the console and are expected to be provided by the operator
Parameters:
    Project:
        Description: 'Project name this cluster is has been created for'
        Type: 'String'
        Default: 'Weapon X'

    Creator:
        Description: 'Tool or person creating this cluster'
        Type: 'String'
        Default: 'CloudFormation'

    Environment:
        Description: 'Context the cluster will be used in.  Common values are production, testing and development.'
        Type: 'String'
        Default: 'development'

    Notes:
        Description: 'Notes to apply, normally edited in the console.'
        Type: 'String'
        Default: 'No notes'

    SshKeyName:
        Description: 'Name of the key to use when creating the EC2 instances'
        Type: 'String'
        Default: 'asgard-lite-test'

    Network:
        Description: 'The ip range to use when building out the VPC network'
        Type: 'String'
        Default: '10.0.0.0'

    InstanceType:
        Description: 'How large of a box to run your containers on'
        Type: 'String'
        Default: 'm4.large'

    SpotPrice:
        Description: 'Maximum bid price to place on your EC2 instances'
        Type: 'String'
        Default: '0.10'

    LoadBalancerPort:
        Description: The port the load balancer should listen on
        Type: Number
        Default: 80

    SearchDomainName:
        Description: 'A name for the Amazon ES domain. Valid characters are a-z (lowercase only), 0-9, and – (hyphen).'
        Type: 'String'

    VpcURL:
        Description: 'Location of the VPC template file'
        Type: 'String'
        Default: 'https://s3.amazonaws.com/jvmguy-cloudformation-templates/vpc.yml'

    EcsURL:
        Description: 'Location of the ECS template file'
        Type: 'String'
        Default: 'https://s3.amazonaws.com/jvmguy-cloudformation-templates/ecs.yml'

    ElbURL:
        Description: 'Location of the ELB template file'
        Type: 'String'
        Default: 'https://s3.amazonaws.com/jvmguy-cloudformation-templates/elb.yml'

    ServiceURL:
        Description: 'Location of the ECS Service template file'
        Type: 'String'
        Default: 'https://s3.amazonaws.com/jvmguy-cloudformation-templates/service.yml'

    CdnURL:
        Description: 'Location of the CDN template file'
        Type: 'String'
        Default: 'https://s3.amazonaws.com/jvmguy-cloudformation-templates/cdn.yml'

    WafURL:
        Description: 'Location of the WAF template file'
        Type: 'String'
        Default: 'https://s3.amazonaws.com/jvmguy-cloudformation-templates/waf.yml'

    CacheURL:
        Description: 'Location of the ElastiCache template file'
        Type: 'String'
        Default: 'https://s3.amazonaws.com/jvmguy-cloudformation-templates/elasticache.yml'

    SearchURL:
        Description: 'Location of the ElasticSearch template file'
        Type: 'String'
        Default: 'https://s3.amazonaws.com/jvmguy-cloudformation-templates/elasticsearch.yml'


Resources:
    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
                Ref: VpcURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes:
                    Ref: Notes
                SshKeyName:
                    Ref: SshKeyName

    Search:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
                Ref: SearchURL
            Parameters:
                DomainName:
                    Ref: SearchDomainName

    Redis:
        Type: AWS::CloudFormation::Stack
        DependsOn: VPC
        Properties:
            TemplateURL:
                Ref: CacheURL
            Parameters:
                VPC:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.VPC
                Subnets:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.PrivateSubnets

    ECS:
        Type: AWS::CloudFormation::Stack
        DependsOn: VPC
        Properties:
            TemplateURL:
                Ref: EcsURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes:
                    Ref: Notes
                SshKeyName:
                    Ref: SshKeyName
                InstanceType:
                    Ref: InstanceType
                SpotPrice:
                    Ref: SpotPrice
                Subnets:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.Subnets
                SecurityGroups:
                    Fn::GetAtt:
                        - VPC
                        - Outputs.SecurityGroupWideOpen

    ExternalLoadBalancer:
        Type: AWS::CloudFormation::Stack
        DependsOn: VPC
        Properties:
            TemplateURL:
                Ref: ElbURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes: 'External Load Balancer'
                Subnets:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.PublicSubnets
                VPC:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.VPC
                SecurityGroups:
                    Fn::GetAtt:
                        - VPC
                        - Outputs.SecurityGroupWideOpen
                LoadBalancerPort:
                    Ref: LoadBalancerPort
                LoadBalancerType: internet-facing

    InternalLoadBalancer:
        Type: AWS::CloudFormation::Stack
        DependsOn: VPC
        Properties:
            TemplateURL:
                Ref: ElbURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes: 'Internal Load Balancer'
                Subnets:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.PrivateSubnets
                VPC:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.VPC
                SecurityGroups:
                    Fn::GetAtt:
                        - VPC
                        - Outputs.SecurityGroupWideOpen
                LoadBalancerPort:
                    Ref: LoadBalancerPort
                LoadBalancerType: internal

    WAF:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
                Ref: WafURL
            Parameters:
                Name:
                    Ref: AWS::StackName
                MetricName:
                    Ref: AWS::StackName
                Priority: 1

    CDN:
        Type: AWS::CloudFormation::Stack
        DependsOn:
            - ExternalLoadBalancer
            - WAF
        Properties:
            TemplateURL:
                Ref: CdnURL
            Parameters:
                LoadBalancerDomainName:
                    Fn::GetAtt:
                        - ExternalLoadBalancer
                        - Outputs.LoadBalancerUrl
                LoadBalancerPort:
                    Ref: LoadBalancerPort
                WAF:
                    Fn::GetAtt:
                        - WAF
                        - Outputs.ACL
                Bucket:
                    Fn::GetAtt:
                        - ExternalLoadBalancer
                        - Outputs.LogBucketDomainName

    Alpha:
        Type: AWS::CloudFormation::Stack
        DependsOn: ExternalLoadBalancer
        Properties:
            TemplateURL:
                Ref: ServiceURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes:
                    Ref: Notes
                VPC:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.VPC
                Cluster:
                    Fn::GetAtt:
                    - ECS
                    - Outputs.Cluster
                Listener:
                    Fn::GetAtt:
                    - ExternalLoadBalancer
                    - Outputs.LoadBalancerListener
                ListenerPriority: 1
                Path: '/alpha'
                ContainerName: 'alpha'
                ServiceFamily:
                    Ref: AWS::StackName
                LoadBalancerPort:
                    Ref: LoadBalancerPort
                LogGroup:
                    Fn::GetAtt:
                        - ECS
                        - Outputs.LogGroup

    Bravo:
        Type: AWS::CloudFormation::Stack
        DependsOn: InternalLoadBalancer
        Properties:
            TemplateURL:
                Ref: ServiceURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes:
                    Ref: Notes
                VPC:
                    Fn::GetAtt:
                    - VPC
                    - Outputs.VPC
                Cluster:
                    Fn::GetAtt:
                    - ECS
                    - Outputs.Cluster
                Listener:
                    Fn::GetAtt:
                    - InternalLoadBalancer
                    - Outputs.LoadBalancerListener
                ListenerPriority: 2
                Path: '/bravo'
                ContainerName: 'bravo'
                ServiceFamily:
                    Ref: AWS::StackName
                LoadBalancerPort:
                    Ref: LoadBalancerPort
                LogGroup:
                    Fn::GetAtt:
                        - ECS
                        - Outputs.LogGroup

Outputs:
    CachedDomainName:
        Description: The DNS name referencing the CDN endpoint
        Value: !GetAtt CDN.Outputs.DomainName

    DirectDomainName:
        Description: The DNS name referencing the uncached external ELB endpoint
        Value: !GetAtt ExternalLoadBalancer.Outputs.LoadBalancerUrl

    InternalDomainName:
        Description: The DNS name referencing the internal ELB endpoint
        Value: !GetAtt InternalLoadBalancer.Outputs.LoadBalancerUrl

    InternalLogBucket:
        Description: The name of the S3 bucket where the internal load balancer places its access logs
        Value: !GetAtt InternalLoadBalancer.Outputs.LogBucket

    ExternalLogBucket:
        Description: The name of the S3 bucket where the external load balancer places its access logs
        Value: !GetAtt ExternalLoadBalancer.Outputs.LogBucket

    RedisAddress:
        Description: The DNS address of the configuration endpoint for the Redis cache cluster.
        Value: !GetAtt Redis.Outputs.Address

    RedisPort:
        Description: The port number of the configuration endpoint for the Redis cache cluster.
        Value: !GetAtt Redis.Outputs.Port

    SearchAddress:
        Description: The domain-specific endpoint that is used to submit index, search, and data upload requests to an Amazon ES domain.
        Value: !GetAtt Search.Outputs.Endpoint
