---
# Cannot get this to work for some reason
#AWSTemplateFormatVersion: AWSTemplateFormatVersion: '2010-09-09'

Description: This template creates a new VPC and places EC2 Container Service (ECS) into it.

Metadata:
    Foo:
        Description: 'something clever'
    Bar:
        Description: 'something clever'

# These show up in the console and are expected to be provided by the operator
Parameters:
    Project:
        Description: 'Project name this cluster is has been created for'
        Type: 'String'
        Default: 'Weapon X'

    Creator:
        Description: 'Tool or person creating this cluster'
        Type: 'String'
        Default: 'CloudFormation'

    Environment:
        Description: 'Context the cluster will be used in.  Common values are production, testing and development.'
        Type: 'String'
        Default: 'development'

    Notes:
        Description: 'Notes to apply, normally edited in the console.'
        Type: 'String'
        Default: 'No notes'

    SshKeyName:
        Description: 'Name of the key to use when creating the EC2 instances'
        Type: 'String'
        Default: 'asgard-lite-test'

    InstanceType:
        Description: 'How large of a box to run your containers on'
        Type: 'String'
        Default: 't2.micro'

    ECSRole:
        Description: 'IAM Role to launch the EC2 instances with'
        Type: 'String'
        Default: 'ecsInstanceRole'

    VpcURL:
        Description: 'Location of the VPC template file'
        Type: 'String'
        Default: 'https://raw.githubusercontent.com/kurron/cloud-formation-vpc/master/vpc.yml'

    EcsURL:
        Description: 'Location of the ECS template file'
        Type: 'String'
        Default: 'https://raw.githubusercontent.com/kurron/cloud-formation-ecs/master/ecs.yml'


Resources:
    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL:
                Ref: VpcURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes:
                    Ref: Notes
                SshKeyName:
                    Ref: SshKeyName
    ECS:
        Type: AWS::CloudFormation::Stack
        DependsOn: VPC
        Properties:
            TemplateURL:
                Ref: EcsURL
            Parameters:
                Project:
                    Ref: Project
                Creator:
                    Ref: Creator
                Environment:
                    Ref: Environment
                Notes:
                    Ref: Notes
                SshKeyName:
                    Ref: SshKeyName
                InstanceType:
                    Ref: InstanceType
                ECSRole:
                    Ref: ECSRole
                PublicSubnetZoneA:
                    - Fn::GetAtt:
                        - VPC
                        - Outputs.PublicSubnetZoneA
                PrivateSubnetZoneA:
                    - Fn::GetAtt:
                        - VPC
                        - Outputs.PrivateSubnetZoneA
                PublicSubnetZoneB:
                    - Fn::GetAtt:
                        - VPC
                        - Outputs.PublicSubnetZoneB
                PrivateSubnetZoneB:
                    - Fn::GetAtt:
                        - VPC
                        - Outputs.PrivateSubnetZoneB
                SecurityGroup:
                    - Fn::GetAtt:
                        - VPC
                        - Outputs.SecurityGroupWideOpen
